// Generated by CoffeeScript 1.3.1
var DOMAIN_PARSER, DomainParser, Domainatrix, Url, fileName, fs;

fs = require("fs");

Url = require("./domainatrix/url");

DomainParser = require("./domainatrix/domain_parser");

fileName = "" + __dirname + "/effective_tld_names.dat";

DOMAIN_PARSER = new DomainParser(fileName);

Domainatrix = (function() {

  Domainatrix.name = 'Domainatrix';

  function Domainatrix() {}

  Domainatrix.parse = function(url) {
    return new Url(DOMAIN_PARSER.parse(url));
  };

  return Domainatrix;

})();

exports.parse = Domainatrix.parse;
